@"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"
choco install -y 7zip
choco install -y androidstudio
choco install -y audacity
choco install -y audacity-lame
choco install -y autohotkey
choco install -y cccp
choco install -y chocolateygui
choco install -y cmdermini
choco install -y firefox
choco install -y flashplayerplugin
choco install -y gitkraken
choco install -y google-backup-and-sync
choco install -y googlechrome
choco install -y inkscape
choco install -y jdk8
choco install -y office365proplus
choco install -y malwarebytes
choco install -y netbeans
choco install -y notepadplusplus
choco install -y pencil
choco install -y pgadmin4
choco install -y qbittorrent
choco install -y steam
choco install -y vlc
choco install -y vmwarevsphereclient
choco install -y vnc-connect
choco install -y vnc-viewer
choco install -y win32diskimager
