@"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"
choco install -y 7zip
choco install -y anaconda3
choco install -y androidstudio
choco install -y audacity
choco install -y audacity-lame
choco install -y autohotkey
choco install -y chocolateygui
choco install -y firefox
choco install -y flashplayerpugin
choco install -y git
choco install -y google-backup-and-sync
choco install -y googlechrome
choco install -y inkscape
choco install -y office365proplus
#oracle-sql-devleoper requires username/password parameters
#choco install -y oracle-sql-developer
choco install -y paint.net
choco install -y partitionwizard
choco install -y pgadmin4
choco install -y powertoys
choco install -y qbittorrent
choco install -y signal
choco install -y sql-server-management-studio
choco install -y steam
choco install -y vlc
choco install -y vnc-viewer
choco install -y vscode
choco install -y win32diskimager
choco install -y windirstat
